"""REST operation names and priority classification."""
from __future__ import annotations

PRIORITY_HIGH = 'HIGH'
PRIORITY_NORMAL = 'NORMAL'
PRIORITY_LOW = 'LOW'

OPERATION_PENDING_FILL_STATUS = 'pending_fill_status'
OPERATION_WORKING_STOP_RECONCILE = 'working_stop_reconcile'
OPERATION_ENTRY_MARKET_DATA = 'entry_market_data'
OPERATION_SPREAD_CLOSE_STATUS = 'spread_close_status'
OPERATION_LONG_CLOSE_STATUS = 'long_close_status'
OPERATION_STOP_PLACE = 'place_stop_order'
OPERATION_STOP_CANCEL = 'cancel_order'
OPERATION_STOP_REPLACE = 'replace_stop_order'
OPERATION_EMERGENCY_CLOSE = 'emergency_close'
OPERATION_RECOVERY_RECONCILE = 'recovery_reconcile'
OPERATION_ALERT_CONFIRM = 'alert_confirm'
OPERATION_FILL_AUDIT = 'fill_audit'
OPERATION_GET_ORDER = 'get_order'
OPERATION_GET_LIVE_ORDERS = 'get_live_orders'
OPERATION_GET_POSITIONS = 'get_positions'
OPERATION_MANUAL_LOOKUP = 'manual_lookup'

OPERATION_PRIORITY = {
    OPERATION_PENDING_FILL_STATUS: PRIORITY_HIGH,
    OPERATION_WORKING_STOP_RECONCILE: PRIORITY_LOW,
    OPERATION_ENTRY_MARKET_DATA: PRIORITY_NORMAL,
    OPERATION_SPREAD_CLOSE_STATUS: PRIORITY_HIGH,
    OPERATION_LONG_CLOSE_STATUS: PRIORITY_HIGH,
    OPERATION_STOP_PLACE: PRIORITY_HIGH,
    OPERATION_STOP_CANCEL: PRIORITY_HIGH,
    OPERATION_STOP_REPLACE: PRIORITY_HIGH,
    OPERATION_EMERGENCY_CLOSE: PRIORITY_HIGH,
    OPERATION_RECOVERY_RECONCILE: PRIORITY_HIGH,
    OPERATION_ALERT_CONFIRM: PRIORITY_HIGH,
    OPERATION_FILL_AUDIT: PRIORITY_LOW,
    OPERATION_GET_ORDER: PRIORITY_NORMAL,
    OPERATION_GET_LIVE_ORDERS: PRIORITY_LOW,
    OPERATION_GET_POSITIONS: PRIORITY_NORMAL,
    OPERATION_MANUAL_LOOKUP: PRIORITY_NORMAL,
    'place_spread_order': PRIORITY_HIGH,
    'place_spread_close_order': PRIORITY_HIGH,
    'place_order': PRIORITY_HIGH,
    'cancel_order': PRIORITY_HIGH,
    'get_order': PRIORITY_NORMAL,
    'get_live_orders': PRIORITY_LOW,
    'get_positions': PRIORITY_NORMAL,
    'broker': PRIORITY_NORMAL,
}


def priority_for_operation(operation: str, *, explicit: str | None = None) -> str:
    if explicit in (PRIORITY_HIGH, PRIORITY_NORMAL, PRIORITY_LOW):
        return explicit
    return OPERATION_PRIORITY.get(operation, PRIORITY_NORMAL)
